### ISSUE TITLE
Crash error for an @ in an input

### ISSUE THREAD

**Issue by guinardA** [react-native-elements/react-native-elements#2463]
Hello,

When I write an email address or a simple @ and validate the content. 
My Expo application closes and the following error appears:
`
java.lang.NullPointerException: Attempt to invoke direct method 'void android.widget.Editor$SelectionModifierCursorController.initDrawables()' on a null object reference
	at android.widget.Editor$SelectionModifierCursorController.access$300(Editor.java:6709)
	at android.widget.Editor.getEmailPopupWindow(Editor.java:1471)
	at android.widget.Editor.showEmailPopupWindow(Editor.java:1479)
	at android.widget.Editor.handleEmailPopup(Editor.java:1458)
	at android.widget.Editor.updateCursorPosition(Editor.java:2101)
	at android.widget.TextView.getUpdatedHighlightPath(TextView.java:7824)
	at android.widget.TextView.onDraw(TextView.java:8009)
	at android.view.View.draw(View.java:21473)
	at android.view.View.updateDisplayListIfDirty(View.java:20350)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3701)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2833)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1796)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7767)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

Expo version : 38.0.0
React Native sdk: 38
React native elements : 2.0.4

**Comment by flyingcircle** [comment]
Code?

**Comment by flyingcircle** [comment]
Verified that input does not crash with @ in input. I suggest debugging your code for null pointers.

**Comment by guinardA** [comment]
This is my code :
`function Settings(props) {
  return (
    <View style={styles.settingsStructure}>
      <TouchableOpacity onPress={() => props.navigation.navigate('Camera')}>
        <Avatar
          rounded
          size='xlarge'
          containerStyle={styles.avatar}
          // eslint-disable-next-line global-require
          source={{
            uri: props.userRedux.img,
          }}
        />
      </TouchableOpacity>

      <View style={styles.name}>
        <Text style={styles.labelName}>{`${
          userMock.userInformation().firstName
        } `}</Text>
        <Text style={styles.labelName}>
          {userMock.userInformation().lastName}
        </Text>
      </View>

      {/* Mobile section */}
      <Input
        placeholder='Votre numéro de téléphone'
        inputStyle={{ color: 'black' }}
        inputContainerStyle={[styles.inputSection]}
        leftIconContainerStyle={styles.inputSectionIcon}
        leftIcon={<Icon name='mobile' size={28} color='#f44336' />}
        keyboardType='phone-pad'
      >
        0299346566
      </Input>

      {/* Mail section */}
      <Input
        placeholder='Votre adresse mail'
        inputStyle={{ color: 'black' }}
        inputContainerStyle={[styles.inputSection]}
        leftIconContainerStyle={styles.inputSectionIcon}
        leftIcon={<Icon name='envelope' size={18} color='#f44336' />}
      >
        prenom@mail.com
      </Input>
    </View>
  );
}

Settings.propTypes = {
  navigation: PropTypes.object,
  userRedux: PropTypes.object,
};

const mapStateToProps = state => ({
  userRedux: state.user,
});

export default connect(mapStateToProps)(Settings);`

I'm sure my input crash  with @ in input or when i write an @ inside my input. 
How do I debug my code for null pointers exception ? Knowing that I just put an input without it being linked.

**Comment by flyingcircle** [comment]
Looks like this is likely a React Native issue?: https://github.com/facebook/react-native/issues/27204
