### ISSUE TITLE
no such file or directory, lstat '.../node_modules/react-native-elements/node_modules/hoist-non-react-statics'

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2503]
Upgrading to react native 62.0 from 61.2

Anyone having this issue?

error: Error: ENOENT: no such file or directory, lstat '/Users/soqqlepteltd/soqqle/soqqleapp/node_modules/react-native-elements/node_modules/hoist-non-react-statics'
    at Object.realpathSync (fs.js:1461:7)
    at DependencyGraph.getSha1 (/Users/soqqlepteltd/soqqle/soqqleapp/node_modules/metro/src/node-haste/DependencyGraph.js:258:29)

**Comment by enigmablue** [comment]
eh sorry i just restarted my metro and it worked.
