### ISSUE TITLE
SearchBar still not working using "Bleeding Edge" Version

### ISSUE THREAD

**Issue by TheSilentHorizon** [react-native-elements/react-native-elements#3123]
So, im trying to get the searchbar to run, but reading all those issues about the searchbar it looks pretty broken.

When trying to install react-native elements via:

`npm install https://github.com/react-native-elements/react-native-elements#dist
`

I can start my expo project but on loading the app, it results in this error crashing the app:

Unable to resolve module ./buttons/Button from <Filepath>\node_modules\react-native-elements\dist\index.js: 

```
None of these files exist:
  * node_modules\react-native-elements\dist\buttons\Button(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules\react-native-elements\dist\buttons\Button\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> 1 | // UI references
  2 | // https://ionicframework.com/docs/components/#buttons
  3 | // https://material.io/guidelines/components/buttons.html#buttons-raised-buttons
  4 | // https://material.angularjs.org/latest/demo/button
```

Searchbar is implemented like this:

```
       headerRight: () => (
                        <View style={{flexDirection:"row"}}>
                            <SearchBar>
                            </SearchBar>
                        </View>
                    )

```
I noticed that the folder structure is different compared to version 3.4.2. Am I missing something? Except the one install code, the documentation has nothing more to offer.

**Comment by arpitBhalla** [comment]
Try reinstalling

**Comment by TheSilentHorizon** [comment]
> Try reinstalling

tried that several times, also tried 3.4.1 but no success either.

**Comment by TheSilentHorizon** [comment]
need to bring this up again, since a searchbar is required for my app. Can anyone tell me how to handle the latest build?

**Comment by flyingcircle** [comment]
@TheSilentHorizon I just saw this error try first deleting your node_modules

```
rm -rf node_modules/react-native-elements
yarn add https://github.com/react-native-elements/react-native-elements#dist 
```

That fixed it for me. I just tested the current `dist` and it works as expected.

**Comment by TheSilentHorizon** [comment]
@flyingcircle Tested it again, same error:

```
None of these files exist:
  * node_modules\react-native-elements\dist\buttons\Button(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules\react-native-elements\dist\buttons\Button\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> 1 | // UI references
  2 | // https://ionicframework.com/docs/components/#buttons
  3 | // https://material.io/guidelines/components/buttons.html#buttons-raised-buttons
  4 | // https://material.angularjs.org/latest/demo/button
    at ModuleResolver.resolveDependency (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at Object.resolve (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\lib\transformHelpers.js:271:42)
    at resolve (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
    at C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Sebas\WebstormProjects\<Project>\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

I use npm instead of yarn, does that maybe make the difference?
