### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by mustafakameldev** [react-native-elements/react-native-elements#3244]
I tried to test a component that has Image, the test failed with an error 

here is the message:   ```● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/mospro/Documents/Pharaohsoft/Mehan360/node_modules/react-native-elements/dist/index.js:6
    import Button from './buttons/Button';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import {useState, useEffect} from 'react';
      3 | import {View} from 'react-native';
    > 4 | import {Image} from 'react-native-elements';
        | ^
      5 | import Loader from '../Loader';
      6 | const CustomImage = ({
      7 |   src,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/components/Image/index.tsx:4:1)```

   react-native-elements : "^3.4.2",
    react-native : "0.66.0"

**Comment by jasonfma** [comment]
I have the same issue - I've gone through and followed the instructions at https://reactnativeelements.com/docs/web_usage/ and I still have the error.

**Comment by mortocks** [comment]
+1 with any element. Example below using a bare bones typescript app but just adding the themeProvider

```
// App.tsx
import { ThemeProvider } from 'react-native-elements';

<ThemeProvider>
  ... Default app snippet
</ThemeProvider>

```

Throws the same error. I'm assuming that this is something to do with the babel config

**Comment by tulio-mcsantos** [comment]
Any news on this?

**Comment by mustafakameldev** [comment]
I solved this issue by adding this line ```"node_modules/(?!(jest-)?@react-native|react-native|react-native-elements/*)",```
on ***transformIgnorePatterns*** array on jest configuration 
to make the whole jest like this:
  ```"jest": {
    "preset": "react-native",
    "globals": {
      "ts-jest": {
        "babelConfig": true
      }
    },
    "testEnvironment": "jsdom",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)?$",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?@react-native|react-native|react-native-flash-message/*)",
      "node_modules/(?!(jest-)?@react-native|react-native|react-native-elements/*)",
    ],
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "cacheDirectory": ".jest/cache",
    "moduleNameMapper": {
      "^.+\\.(css|less|scss)$": "identity-obj-proxy"
    }
  }```
hope It will work  for you @tulio-mcsantos

**Comment by tulio-mcsantos** [comment]
Worked like a charm!! Thanks a lot @mustafakameldev
