### ISSUE TITLE
Bleeding Edge Build Fail 

### ISSUE THREAD

**Issue by arpitBhalla** [react-native-elements/react-native-elements#3417]
## Follow up https://github.com/react-native-elements/react-native-elements/issues/3399#issuecomment-1079906837

expo EAS can't build 4.0.0-rc.0 because we need to firstly run npm login,but I don't know how to do it with expo EAS.Is there a way to install @react-native-elements(4.0.0-rc.0) without login?

I have tried `yarn add @react-native-elements/base@react-native-elements/react-native-elements#base` but I met error when run gradlew:
`
> Task :app:checkReleaseAarMetadata
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
Fast - Scalable - Integrated
[stderr] error node_modules/@react-native-elements/base/node_modules/color/index.js: Unexpected token: name (_28) in file node_modules/@react-native-elements/base/node_modules/color/index.js at 255:33.
Error: Unexpected token: name (_28) in file node_modules/@react-native-elements/base/node_modules/color/index.js at 255:33
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:279:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:146:24)
    at _next (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:168:9)
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:175:7
    at new Promise (<anonymous>)
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:164:12
    at minifyCode (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:289:17)
    at Object.<anonymous> (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:569:40)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 51s
`

I don't know if `yarn add @react-native-elements/base@react-native-elements/react-native-elements#base` is causing this problem...
 
_Originally posted by @shadowfish07 in https://github.com/react-native-elements/react-native-elements/issues/3399#issuecomment-1079906837_

**Comment by arpitBhalla** [comment]
I believe it's because, color(v4) is using >=ES2021 and your config doesn;t support ES2021

https://github.com/Qix-/color/blob/286fb710033e7a915003c9cdc3a2522a38d9c8a3/index.js#L272

**Comment by arpitBhalla** [comment]
Reverted to Color v3
