### ISSUE TITLE
Testing with Jest - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by IlirBajrami** [react-native-elements/react-native-elements#3695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Trying to test my app with Jest. I'm having a button imported from `rneui`. `import {Button} from '@rneui/themed';`

### Expected behavior

The Jest test to pass.

### Describe the bug

`Details:

    /Users/ilirbajrami/Desktop/MoneyliaApp/node_modules/@rneui/themed/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { AirbnbRatingDefault as AirbnbRating, } from './AirbnbRating';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module`

If i delete the button or import it from `react-native` the test passes.

### Steps To Reproduce

```Markdown
import button from `@rneui/themed` and try to test the component where the button is imported.
```

### Screenshots

![Screenshot 2022-12-02 at 02 30 33](https://user-images.githubusercontent.com/22265824/205194304-308c23b5-828d-4c57-9d5e-dcdc71a7d51c.png)

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
        ## Local Dependencies:

 - @rneui/base : ^4.0.0-rc.7
 - @rneui/themed : ^4.0.0-rc.7
 - react : 18.1.0
 - react-native : 0.70.6
 - @types/react : ^18.0.21
 - @types/react-native : ^0.70.6
      ```

</details>

**Comment by Alaa-Ben** [comment]
Usually, when you get this kind of errors, it's due to the jest setup.
You should have a config file somewhere (jest.config.js for example), in there add @rneui:
```
 transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native(-.*)?|@react-native(-community)?|@rneui)/)'
  ],
```

**Comment by nielsdaw** [comment]
Like @Alaa-Ben mentioned; jest requires that you set transformIgnorePatterns for libraries that need to be transformed by babel. 

As already proposed; I fixed this by adding `@rneui` to the transformIgnorePatterns list.

**Comment by Jeet989** [comment]
After adding `@rneui` still I am getting this error. Here is the screenshot for the issue and also the code that I am using in package.json

`  "transformIgnorePatterns": [
      "/node_modules/(?!(react-native|@react-native|@react-navigation|react-native-reanimated|@rneui)/)"
    ]`


<img width="1327" alt="image" src="https://user-images.githubusercontent.com/40856822/221675602-45085b1d-10e4-48f7-b8ab-5105db4feecd.png">

**Comment by Alaa-Ben** [comment]
The non transformed module seemed to be react-native-size-matters
as a rule of thumb, I transformed using a regex every react-native-* package
so try something like:
```
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native(-.*)?|@react-native(-community)?|@react-navigation|@rneui)/)'
  ],
```

**Comment by dataheadless** [comment]
This article may help as it covers few possible solutions [Jest and ESM](https://techkluster.com/node/jest-and-esm/)

**Comment by mayankjaiswal1709** [comment]
![Screenshot (4)](https://github.com/react-native-elements/react-native-elements/assets/58311460/3b5f4bf6-390d-4ddd-a261-5a700001640a)

This error coming again and  again ,
 neither the proper solution is found nor this error is gone. If anyone knows the solution please let me know.

**Comment by otaviolbarbosa** [comment]
@mayankjaiswal1709 any updates? I got the same issue here

**Comment by ufolux** [comment]
Same problem here

```
Details:

    /Users/sines/Code/GithubProj/AwesomeSplit/node_modules/.pnpm/react-native@0.73.4_@babel+core@7.23.9_@babel+preset-env@7.23.9_react@18.2.0/node_modules/react-native/index.js:14
    import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 |  */
      4 |
    > 5 | import 'react-native';
        | ^
      6 | import React from 'react';
      7 | import App from '../App';
      8 |

      at Runtime.createScriptFromCode (node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (__tests__/App.test.tsx:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.351 s
```

**Comment by KinTsume** [comment]
In my case even adding in the transformIgnorePattern the error didn't change
