### ISSUE TITLE
Creating a new app with `create-expo-app --template @rneui/template`

### ISSUE THREAD

**Issue by jkieley** [react-native-elements/react-native-elements#3754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

```
npx create-expo-app --template @rneui/template
npx expo install @expo/webpack-config@^0.17.2
npm run web
```
Leads to the follow error on page load
```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /app/node_modules/react-native-safe-area-context/lib/module/index.js: Cannot read properties of undefined (reading '0')
    at new SourceMap (:19006/app/node_modules/@babel/generator/lib/source-map.js:29:99)
    at new Generator (:19006/app/node_modules/@babel/generator/lib/index.js:13:35)
    at generate (:19006/app/node_modules/@babel/generator/lib/index.js:88:15)
    at generateCode (:19006/app/node_modules/@babel/core/lib/transformation/file/generate.js:47:39)
    at run (:19006/app/node_modules/@babel/core/lib/transformation/index.js:39:33)
    at run.next (<anonymous>)
    at transform (:19006/app/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (:19006/app/node_modules/gensync/index.js:261:32)
    at :19006/app/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (:19006/app/node_modules/gensync/index.js:223:11)
    at :19006/app/node_modules/gensync/index.js:189:28
    at :19006/app/node_modules/@babel/core/lib/gensync-utils/async.js:68:7
    at :19006/app/node_modules/gensync/index.js:113:33
    at step (:19006/app/node_modules/gensync/index.js:287:14)
    at :19006/app/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (:19006/app/node_modules/gensync/index.js:223:11)
    at ./node_modules/react-native-safe-area-context/lib/module/index.js (index.js:2:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@rneui/base/dist/BottomSheet/BottomSheet.js (BottomSheet.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@rneui/themed/dist/BottomSheet/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@rneui/themed/dist/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (App.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
VM29:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)
index.js:1 ./node_modules/react-native-safe-area-context/lib/module/index.js
TypeError: /app/node_modules/react-native-safe-area-context/lib/module/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```

### Expected behavior

After creating a new app from a template, the first page should run without errors.

### Describe the bug

Leads to the follow error on page load

### Steps To Reproduce

```Markdown
npx create-expo-app --template @rneui/template
npx expo install @expo/webpack-config@^0.17.2
npm run web
```
```


### Screenshots

_No response_

### Your Environment

<details>
<summary>`npx @rneui/envinfo`</summary>

      ```
React Native Elements Env Info

## Global Dependencies:

 - expo-cli : 6.3.1

## Local Dependencies:

 - expo : ^47.0.12
 - react : 17.0.1
 - react-native : 0.64.3
 - @rneui/base : 4.0.0-rc.7
 - @rneui/themed : 4.0.0-rc.7
 - @types/react : ~17.0.21
 - @types/react-native : ~0.64.12

      ```

</details>

**Comment by jkieley** [comment]
Looks like installing the peer dependencies resolved this. 
https://reactnativeelements.com/docs/installation#peer-dependencies
